# Generated by Django 4.2.1 on 2023-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
