# Generated by Django 4.2.1 on 2023-08-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_timestamp_message_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='times',
            new_name='timestamp',
        ),
    ]
