# Generated by Django 4.2.1 on 2023-08-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Message', # モデル名
            old_name='message',   # 変更前
            new_name='text'    # 変更後
        )
    ]
